# Generated by Django 3.1.1 on 2022-06-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'ordering': ('-id',), 'verbose_name': 'Fayl', 'verbose_name_plural': 'Fayllar'},
        ),
        migrations.RemoveField(
            model_name='files',
            name='created',
        ),
        migrations.RemoveField(
            model_name='files',
            name='description',
        ),
        migrations.RemoveField(
            model_name='files',
            name='slug',
        ),
        migrations.AddField(
            model_name='files',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='file_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='name',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='files',
            name='type',
            field=models.CharField(choices=[('video', 'Video'), ('book', 'Book'), ('prog', 'Programma')], default='book', max_length=20),
        ),
    ]
