# Generated by Django 3.1.1 on 2022-06-23 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_auto_20220622_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Savol')),
                ('period', models.IntegerField(default=10, verbose_name='Vaqt')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='TestOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Savol javobi')),
                ('is_correct', models.BooleanField(default=False)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.test')),
            ],
            options={
                'verbose_name': 'Test savol javobi',
                'verbose_name_plural': 'Test savol javoblari',
                'ordering': ('-id',),
            },
        ),
    ]
