# Generated by Django 3.1.1 on 2022-06-23 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_test_testoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='period',
        ),
        migrations.AlterField(
            model_name='testoption',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tgbot.test'),
        ),
        migrations.CreateModel(
            name='TestAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answers', models.IntegerField(default=0)),
                ('given_tests', models.ManyToManyField(blank=True, null=True, to='tgbot.Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.user')),
            ],
        ),
    ]
