# Generated by Django 3.1.1 on 2022-06-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_auto_20220623_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testanswers',
            name='given_tests',
            field=models.ManyToManyField(blank=True, to='tgbot.Test'),
        ),
    ]
