# Generated by Django 3.1.1 on 2022-06-23 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_auto_20220623_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='testanswers',
            name='current_test',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='testanswers',
            name='total_test',
            field=models.IntegerField(default=10),
        ),
    ]
